required_environment_variables = [
  'DISCORD_BOT_TOKEN'
]

base_guild_id = '1253092552404631582'

[server]
port = 3003

[server.socket]
heartbeat_interval = 30000

[server.socket.opcodes]
HELLO = 1
INIT = 2
INIT_ACK = 3
HEARTBEAT = 4
HEARTBEAT_ACK = 5
PRESENCE_UPDATE = 6
USER_LEFT = 7
USER_JOINED = 8
DISCONNECT = 9

[logger.levels]
error = 'red'
warn = 'yellow'
info = 'blue'
debug = 'grey'
database = 'magenta'
bot = 'green'
http = 'yellow'
socket = 'cyan'

[user_svg_card.colors.dark]
  background = '#17171c'
  background_secondary = '#1e1e24'
  card = '#1e1e24'

[user_svg_card.colors.dark.text]
  primary = '#ffffff'
  secondary = '#999999'

[user_svg_card.colors.light]
  background = '#e6e6e6'
  background_secondary = '#dcdcdc'
  card = '#eeeeee'

[user_svg_card.colors.light.text]
  primary = '#242a31'
  secondary = '#6c757d'